language: python
sudo: false
env:
  global:
  - PYTHONPATH=.
  - DISPLAY=:99.0
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
before_script:
- sh -e /etc/init.d/xvfb start
- sleep 3 # give xvfb some time to start
script:
- py.test -s
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
