language: python
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: "pip install -r requirements_dev.txt --use-mirrors"

script: py.test test && lettuce

env: PYTHONPATH=.

python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "pypy"
